config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.4
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  NOGPU: 'true'
sqa_criteria:
  QC.Lic:
    repos:
      this_repo:
        commands:
        - licensee detect . --json
        container: qc.lic_silly-orchid-corgi
timeout: 1800
